# Time::DATE_FORMATS[:datetime_jp] = '%Y %m/%d %H:%M'
Time::DATE_FORMATS[:datetime_jp] = '%m/%d %H:%M'
Time::DATE_FORMATS[:datetime_jp_clock] = '%H:%M'
Time::DATE_FORMATS[:datetime_jp_date] = '%m/%d'
Time::DATE_FORMATS[:time_clock] = '%H'
